
-- 1 PostgreSQL database account type enumeration
CREATE TYPE public.account_type AS ENUM
    ('Client', 'Employee', 'Admin');

ALTER TYPE public.account_type
    OWNER TO cse340;


-- 2 Table structure for table 'classification'
CREATE TABLE PUBLIC.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- 3 Table structure for table 'inventory'
CREATE TABLE PUBLIC.inventory (
    inv_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_make CHARACTER VARYING NOT NULL,
    inv_model CHARACTER VARYING NOT NULL,
    inv_year CHARACTER(4) NOT NULL,
    inv_description TEXT NOT NULL,
    inv_image CHARACTER VARYING NOT NULL,
    inv_thumbnail CHARACTER VARYING NOT NULL,
    inv_price NUMERIC(9,0) NOT NULL,
    inv_miles INTEGER NOT NULL,
    inv_color CHARACTER VARYING NOT NULL,
    classification_id INTEGER NOT NULL,
    CONSTRAINT inventory_pk PRIMARY KEY (inv_id)
);
--4 Create relationship between 'classification' and 'inventory' tables
ALTER TABLE IF EXISTS PUBLIC.inventory
    ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
    REFERENCES PUBLIC.classification (classification_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION;


--5 Table structure for table 'account'
CREATE TABLE IF NOT EXISTS PUBLIC.account (
    account_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname CHARACTER VARYING NOT NULL,
    account_lastname CHARACTER VARYING NOT NULL,
    account_email CHARACTER VARYING NOT NULL,
    account_password CHARACTER VARYING NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);